export const apiData = [
  {
    title: "Super AI",
    description: "An advanced AI-powered assistant for developers.",
    rating: 4.8,
    installs: 12000,
    price: "$9.99/month",
  },
  {
    title: "Code Helper",
    description: "A smart tool that helps you write better code.",
    rating: 4.5,
    installs: 8500,
    price: "Free",
  },
  {
    title: "Design Genie",
    description: "AI-driven design recommendations for UI/UX enthusiasts.",
    rating: 4.7,
    installs: 5000,
    price: "$14.99/month",
  },
  {
    title: "Music Maker",
    description: "Generate high-quality music with AI assistance.",
    rating: 4.3,
    installs: 7200,
    price: "Free",
  },
  {
    title: "Data Cruncher",
    description: "Process and analyze big data efficiently.",
    rating: 4.6,
    installs: 9400,
    price: "$19.99/month",
  },
  {
    title: "Image Enhancer",
    description: "Enhance image quality using AI upscaling.",
    rating: 4.9,
    installs: 15000,
    price: "$7.99/month",
  },
  {
    title: "Speech to Text Pro",
    description: "Accurately transcribe audio into text.",
    rating: 4.4,
    installs: 6300,
    price: "Free",
  },
  {
    title: "Stock Predictor",
    description: "AI-powered predictions for stock markets.",
    rating: 4.2,
    installs: 4600,
    price: "$29.99/month",
  },
  {
    title: "Weather AI",
    description: "Real-time weather forecasting with AI models.",
    rating: 4.7,
    installs: 8800,
    price: "Free",
  },
  {
    title: "Crypto Tracker",
    description: "Track and analyze cryptocurrency trends.",
    rating: 4.5,
    installs: 10200,
    price: "$5.99/month",
  },
];
